// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: local_database/local_database.proto

package local_database

import (
	sdk_ws "Open_IM/pkg/proto/sdk_ws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type SyncDataMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType string `protobuf:"bytes,1,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MsgData string `protobuf:"bytes,3,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
}

func (x *SyncDataMsg) Reset() {
	*x = SyncDataMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataMsg) ProtoMessage() {}

func (x *SyncDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataMsg.ProtoReflect.Descriptor instead.
func (*SyncDataMsg) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{1}
}

func (x *SyncDataMsg) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *SyncDataMsg) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SyncDataMsg) GetMsgData() string {
	if x != nil {
		return x.MsgData
	}
	return ""
}

type SyncDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID    string                        `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	MsgType        string                        `protobuf:"bytes,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MemberIDList   []string                      `protobuf:"bytes,3,rep,name=MemberIDList,proto3" json:"MemberIDList,omitempty"`
	GroupInfo      *sdk_ws.GroupInfo             `protobuf:"bytes,4,opt,name=GroupInfo,proto3" json:"GroupInfo,omitempty"`
	Conversation   *sdk_ws.Conversation          `protobuf:"bytes,5,opt,name=Conversation,proto3" json:"Conversation,omitempty"`
	GroupRequest   *sdk_ws.GroupRequest          `protobuf:"bytes,6,opt,name=GroupRequest,proto3" json:"GroupRequest,omitempty"`
	FriendRequest  *sdk_ws.FriendRequest         `protobuf:"bytes,7,opt,name=FriendRequest,proto3" json:"FriendRequest,omitempty"`
	FriendInfo     *sdk_ws.FriendInfo            `protobuf:"bytes,8,opt,name=FriendInfo,proto3" json:"FriendInfo,omitempty"`
	BlackInfo      *sdk_ws.BlackInfo             `protobuf:"bytes,9,opt,name=BlackInfo,proto3" json:"BlackInfo,omitempty"`
	UserInfo       *sdk_ws.UserInfo              `protobuf:"bytes,10,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	MemberInfoList []*sdk_ws.GroupMemberFullInfo `protobuf:"bytes,11,rep,name=memberInfoList,proto3" json:"memberInfoList,omitempty"`
	MsgList        []*sdk_ws.MsgData             `protobuf:"bytes,12,rep,name=msgList,proto3" json:"msgList,omitempty"`
}

func (x *SyncDataReq) Reset() {
	*x = SyncDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataReq) ProtoMessage() {}

func (x *SyncDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataReq.ProtoReflect.Descriptor instead.
func (*SyncDataReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{2}
}

func (x *SyncDataReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncDataReq) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *SyncDataReq) GetMemberIDList() []string {
	if x != nil {
		return x.MemberIDList
	}
	return nil
}

func (x *SyncDataReq) GetGroupInfo() *sdk_ws.GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *SyncDataReq) GetConversation() *sdk_ws.Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *SyncDataReq) GetGroupRequest() *sdk_ws.GroupRequest {
	if x != nil {
		return x.GroupRequest
	}
	return nil
}

func (x *SyncDataReq) GetFriendRequest() *sdk_ws.FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

func (x *SyncDataReq) GetFriendInfo() *sdk_ws.FriendInfo {
	if x != nil {
		return x.FriendInfo
	}
	return nil
}

func (x *SyncDataReq) GetBlackInfo() *sdk_ws.BlackInfo {
	if x != nil {
		return x.BlackInfo
	}
	return nil
}

func (x *SyncDataReq) GetUserInfo() *sdk_ws.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *SyncDataReq) GetMemberInfoList() []*sdk_ws.GroupMemberFullInfo {
	if x != nil {
		return x.MemberInfoList
	}
	return nil
}

func (x *SyncDataReq) GetMsgList() []*sdk_ws.MsgData {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type InitDataBaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OperationID string `protobuf:"bytes,2,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
}

func (x *InitDataBaseReq) Reset() {
	*x = InitDataBaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitDataBaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDataBaseReq) ProtoMessage() {}

func (x *InitDataBaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDataBaseReq.ProtoReflect.Descriptor instead.
func (*InitDataBaseReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{3}
}

func (x *InitDataBaseReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *InitDataBaseReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type SyncGroupMemberInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OperationID string `protobuf:"bytes,2,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	GroupID     string `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *SyncGroupMemberInfoReq) Reset() {
	*x = SyncGroupMemberInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncGroupMemberInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupMemberInfoReq) ProtoMessage() {}

func (x *SyncGroupMemberInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupMemberInfoReq.ProtoReflect.Descriptor instead.
func (*SyncGroupMemberInfoReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGroupMemberInfoReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SyncGroupMemberInfoReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncGroupMemberInfoReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type SyncGroupMemberListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MemberList  string `protobuf:"bytes,3,opt,name=memberList,proto3" json:"memberList,omitempty"`
}

func (x *SyncGroupMemberListReq) Reset() {
	*x = SyncGroupMemberListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncGroupMemberListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupMemberListReq) ProtoMessage() {}

func (x *SyncGroupMemberListReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupMemberListReq.ProtoReflect.Descriptor instead.
func (*SyncGroupMemberListReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{5}
}

func (x *SyncGroupMemberListReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncGroupMemberListReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SyncGroupMemberListReq) GetMemberList() string {
	if x != nil {
		return x.MemberList
	}
	return ""
}

type KickGroupMemberForAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	GroupID     string `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	KickedID    string `protobuf:"bytes,3,opt,name=kickedID,proto3" json:"kickedID,omitempty"`
}

func (x *KickGroupMemberForAllReq) Reset() {
	*x = KickGroupMemberForAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickGroupMemberForAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickGroupMemberForAllReq) ProtoMessage() {}

func (x *KickGroupMemberForAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickGroupMemberForAllReq.ProtoReflect.Descriptor instead.
func (*KickGroupMemberForAllReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{6}
}

func (x *KickGroupMemberForAllReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *KickGroupMemberForAllReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *KickGroupMemberForAllReq) GetKickedID() string {
	if x != nil {
		return x.KickedID
	}
	return ""
}

type DeleteGroupMembersForAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	GroupID     string `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *DeleteGroupMembersForAllReq) Reset() {
	*x = DeleteGroupMembersForAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupMembersForAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupMembersForAllReq) ProtoMessage() {}

func (x *DeleteGroupMembersForAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupMembersForAllReq.ProtoReflect.Descriptor instead.
func (*DeleteGroupMembersForAllReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGroupMembersForAllReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *DeleteGroupMembersForAllReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type SyncUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *SyncUserInfoReq) Reset() {
	*x = SyncUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserInfoReq) ProtoMessage() {}

func (x *SyncUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserInfoReq.ProtoReflect.Descriptor instead.
func (*SyncUserInfoReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{8}
}

func (x *SyncUserInfoReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncUserInfoReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type SyncAddFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FriendID    string `protobuf:"bytes,3,opt,name=FriendID,proto3" json:"FriendID,omitempty"`
	OperatorID  string `protobuf:"bytes,4,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
}

func (x *SyncAddFriendReq) Reset() {
	*x = SyncAddFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAddFriendReq) ProtoMessage() {}

func (x *SyncAddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAddFriendReq.ProtoReflect.Descriptor instead.
func (*SyncAddFriendReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{9}
}

func (x *SyncAddFriendReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncAddFriendReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SyncAddFriendReq) GetFriendID() string {
	if x != nil {
		return x.FriendID
	}
	return ""
}

func (x *SyncAddFriendReq) GetOperatorID() string {
	if x != nil {
		return x.OperatorID
	}
	return ""
}

type SyncConversationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID    string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	OwnerID        string `protobuf:"bytes,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	ConversationID string `protobuf:"bytes,3,opt,name=ConversationID,proto3" json:"ConversationID,omitempty"`
}

func (x *SyncConversationReq) Reset() {
	*x = SyncConversationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_database_local_database_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConversationReq) ProtoMessage() {}

func (x *SyncConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_database_local_database_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConversationReq.ProtoReflect.Descriptor instead.
func (*SyncConversationReq) Descriptor() ([]byte, []int) {
	return file_local_database_local_database_proto_rawDescGZIP(), []int{10}
}

func (x *SyncConversationReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *SyncConversationReq) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *SyncConversationReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

var File_local_database_local_database_proto protoreflect.FileDescriptor

var file_local_database_local_database_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x5f, 0x77, 0x73, 0x2f, 0x77,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x22, 0xb5, 0x05, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61,
	0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x43,
	0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3d, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3a, 0x0a, 0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4e, 0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61,
	0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x0f, 0x49, 0x6e,
	0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x6c, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x72, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x18, 0x4b, 0x69, 0x63,
	0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x49, 0x44, 0x22, 0x59, 0x0a,
	0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x64,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44,
	0x22, 0x79, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x32, 0x54, 0x0a, 0x0d, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08,
	0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x3b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_local_database_local_database_proto_rawDescOnce sync.Once
	file_local_database_local_database_proto_rawDescData = file_local_database_local_database_proto_rawDesc
)

func file_local_database_local_database_proto_rawDescGZIP() []byte {
	file_local_database_local_database_proto_rawDescOnce.Do(func() {
		file_local_database_local_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_local_database_local_database_proto_rawDescData)
	})
	return file_local_database_local_database_proto_rawDescData
}

var file_local_database_local_database_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_local_database_local_database_proto_goTypes = []interface{}{
	(*CommonResp)(nil),                  // 0: local_database.CommonResp
	(*SyncDataMsg)(nil),                 // 1: local_database.SyncDataMsg
	(*SyncDataReq)(nil),                 // 2: local_database.SyncDataReq
	(*InitDataBaseReq)(nil),             // 3: local_database.InitDataBaseReq
	(*SyncGroupMemberInfoReq)(nil),      // 4: local_database.SyncGroupMemberInfoReq
	(*SyncGroupMemberListReq)(nil),      // 5: local_database.SyncGroupMemberListReq
	(*KickGroupMemberForAllReq)(nil),    // 6: local_database.KickGroupMemberForAllReq
	(*DeleteGroupMembersForAllReq)(nil), // 7: local_database.DeleteGroupMembersForAllReq
	(*SyncUserInfoReq)(nil),             // 8: local_database.SyncUserInfoReq
	(*SyncAddFriendReq)(nil),            // 9: local_database.SyncAddFriendReq
	(*SyncConversationReq)(nil),         // 10: local_database.SyncConversationReq
	(*sdk_ws.GroupInfo)(nil),            // 11: server_api_params.GroupInfo
	(*sdk_ws.Conversation)(nil),         // 12: server_api_params.Conversation
	(*sdk_ws.GroupRequest)(nil),         // 13: server_api_params.GroupRequest
	(*sdk_ws.FriendRequest)(nil),        // 14: server_api_params.FriendRequest
	(*sdk_ws.FriendInfo)(nil),           // 15: server_api_params.FriendInfo
	(*sdk_ws.BlackInfo)(nil),            // 16: server_api_params.BlackInfo
	(*sdk_ws.UserInfo)(nil),             // 17: server_api_params.UserInfo
	(*sdk_ws.GroupMemberFullInfo)(nil),  // 18: server_api_params.GroupMemberFullInfo
	(*sdk_ws.MsgData)(nil),              // 19: server_api_params.MsgData
}
var file_local_database_local_database_proto_depIdxs = []int32{
	11, // 0: local_database.SyncDataReq.GroupInfo:type_name -> server_api_params.GroupInfo
	12, // 1: local_database.SyncDataReq.Conversation:type_name -> server_api_params.Conversation
	13, // 2: local_database.SyncDataReq.GroupRequest:type_name -> server_api_params.GroupRequest
	14, // 3: local_database.SyncDataReq.FriendRequest:type_name -> server_api_params.FriendRequest
	15, // 4: local_database.SyncDataReq.FriendInfo:type_name -> server_api_params.FriendInfo
	16, // 5: local_database.SyncDataReq.BlackInfo:type_name -> server_api_params.BlackInfo
	17, // 6: local_database.SyncDataReq.UserInfo:type_name -> server_api_params.UserInfo
	18, // 7: local_database.SyncDataReq.memberInfoList:type_name -> server_api_params.GroupMemberFullInfo
	19, // 8: local_database.SyncDataReq.msgList:type_name -> server_api_params.MsgData
	2,  // 9: local_database.LocalDataBase.SyncData:input_type -> local_database.SyncDataReq
	0,  // 10: local_database.LocalDataBase.SyncData:output_type -> local_database.CommonResp
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_local_database_local_database_proto_init() }
func file_local_database_local_database_proto_init() {
	if File_local_database_local_database_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_local_database_local_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitDataBaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncGroupMemberInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncGroupMemberListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickGroupMemberForAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupMembersForAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAddFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_database_local_database_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConversationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_local_database_local_database_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_local_database_local_database_proto_goTypes,
		DependencyIndexes: file_local_database_local_database_proto_depIdxs,
		MessageInfos:      file_local_database_local_database_proto_msgTypes,
	}.Build()
	File_local_database_local_database_proto = out.File
	file_local_database_local_database_proto_rawDesc = nil
	file_local_database_local_database_proto_goTypes = nil
	file_local_database_local_database_proto_depIdxs = nil
}
