// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: appversion/appversion.proto

package appversion

import (
	sdk_ws "Open_IM/pkg/proto/sdk_ws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type AppVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Type        int32  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Status      int32  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Isforce     int32  `protobuf:"varint,5,opt,name=Isforce,proto3" json:"Isforce,omitempty"`
	Title       string `protobuf:"bytes,6,opt,name=Title,proto3" json:"Title,omitempty"`
	DownloadUrl string `protobuf:"bytes,7,opt,name=DownloadUrl,proto3" json:"DownloadUrl,omitempty"`
	Content     string `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime  int64  `protobuf:"varint,9,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	CreateUser  string `protobuf:"bytes,10,opt,name=CreateUser,proto3" json:"CreateUser,omitempty"`
	UpdateTime  int64  `protobuf:"varint,11,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	UpdateUser  string `protobuf:"bytes,12,opt,name=UpdateUser,proto3" json:"UpdateUser,omitempty"`
}

func (x *AppVersion) Reset() {
	*x = AppVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVersion) ProtoMessage() {}

func (x *AppVersion) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVersion.ProtoReflect.Descriptor instead.
func (*AppVersion) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{1}
}

func (x *AppVersion) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AppVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppVersion) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AppVersion) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AppVersion) GetIsforce() int32 {
	if x != nil {
		return x.Isforce
	}
	return 0
}

func (x *AppVersion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AppVersion) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *AppVersion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppVersion) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AppVersion) GetCreateUser() string {
	if x != nil {
		return x.CreateUser
	}
	return ""
}

func (x *AppVersion) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *AppVersion) GetUpdateUser() string {
	if x != nil {
		return x.UpdateUser
	}
	return ""
}

type GetAppVersionByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	ID          string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetAppVersionByIDReq) Reset() {
	*x = GetAppVersionByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppVersionByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionByIDReq) ProtoMessage() {}

func (x *GetAppVersionByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionByIDReq.ProtoReflect.Descriptor instead.
func (*GetAppVersionByIDReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppVersionByIDReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *GetAppVersionByIDReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetAppVersionByIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appversion *AppVersion `protobuf:"bytes,1,opt,name=appversion,proto3" json:"appversion,omitempty"`
}

func (x *GetAppVersionByIDResp) Reset() {
	*x = GetAppVersionByIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppVersionByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionByIDResp) ProtoMessage() {}

func (x *GetAppVersionByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionByIDResp.ProtoReflect.Descriptor instead.
func (*GetAppVersionByIDResp) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppVersionByIDResp) GetAppversion() *AppVersion {
	if x != nil {
		return x.Appversion
	}
	return nil
}

type GetLatestAppVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	Client      string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *GetLatestAppVersionReq) Reset() {
	*x = GetLatestAppVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestAppVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAppVersionReq) ProtoMessage() {}

func (x *GetLatestAppVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAppVersionReq.ProtoReflect.Descriptor instead.
func (*GetLatestAppVersionReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestAppVersionReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *GetLatestAppVersionReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type GetLatestAppVersionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appversion *AppVersion `protobuf:"bytes,1,opt,name=appversion,proto3" json:"appversion,omitempty"`
}

func (x *GetLatestAppVersionResp) Reset() {
	*x = GetLatestAppVersionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestAppVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAppVersionResp) ProtoMessage() {}

func (x *GetLatestAppVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAppVersionResp.ProtoReflect.Descriptor instead.
func (*GetLatestAppVersionResp) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestAppVersionResp) GetAppversion() *AppVersion {
	if x != nil {
		return x.Appversion
	}
	return nil
}

type GetAppVersionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID     string                    `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	Pagination      *sdk_ws.RequestPagination `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	Client          string                    `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Status          string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateTimeBegin string                    `protobuf:"bytes,5,opt,name=createTimeBegin,proto3" json:"createTimeBegin,omitempty"`
	CreateTimeEnd   string                    `protobuf:"bytes,6,opt,name=createTimeEnd,proto3" json:"createTimeEnd,omitempty"`
	OrderBy         string                    `protobuf:"bytes,7,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
}

func (x *GetAppVersionsReq) Reset() {
	*x = GetAppVersionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionsReq) ProtoMessage() {}

func (x *GetAppVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionsReq.ProtoReflect.Descriptor instead.
func (*GetAppVersionsReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{6}
}

func (x *GetAppVersionsReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *GetAppVersionsReq) GetPagination() *sdk_ws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetAppVersionsReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *GetAppVersionsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAppVersionsReq) GetCreateTimeBegin() string {
	if x != nil {
		return x.CreateTimeBegin
	}
	return ""
}

func (x *GetAppVersionsReq) GetCreateTimeEnd() string {
	if x != nil {
		return x.CreateTimeEnd
	}
	return ""
}

func (x *GetAppVersionsReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GetAppVersionsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appversions []*AppVersion              `protobuf:"bytes,1,rep,name=appversions,proto3" json:"appversions,omitempty"`
	Pagination  *sdk_ws.ResponsePagination `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	Total       int32                      `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetAppVersionsResp) Reset() {
	*x = GetAppVersionsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppVersionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppVersionsResp) ProtoMessage() {}

func (x *GetAppVersionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppVersionsResp.ProtoReflect.Descriptor instead.
func (*GetAppVersionsResp) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppVersionsResp) GetAppversions() []*AppVersion {
	if x != nil {
		return x.Appversions
	}
	return nil
}

func (x *GetAppVersionsResp) GetPagination() *sdk_ws.ResponsePagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetAppVersionsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddAppVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Client      string `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Isforce     int32  `protobuf:"varint,4,opt,name=isforce,proto3" json:"isforce,omitempty"`
	Title       string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	DownloadUrl string `protobuf:"bytes,6,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	Remark      string `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Status      int32  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Type        int32  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	UserID      string `protobuf:"bytes,10,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *AddAppVersionReq) Reset() {
	*x = AddAppVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAppVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppVersionReq) ProtoMessage() {}

func (x *AddAppVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppVersionReq.ProtoReflect.Descriptor instead.
func (*AddAppVersionReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{8}
}

func (x *AddAppVersionReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *AddAppVersionReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AddAppVersionReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *AddAppVersionReq) GetIsforce() int32 {
	if x != nil {
		return x.Isforce
	}
	return 0
}

func (x *AddAppVersionReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddAppVersionReq) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *AddAppVersionReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddAppVersionReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddAppVersionReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AddAppVersionReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type EditAppVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OperationID string `protobuf:"bytes,2,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Client      string `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Isforce     int32  `protobuf:"varint,5,opt,name=isforce,proto3" json:"isforce,omitempty"`
	Title       string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	DownloadUrl string `protobuf:"bytes,7,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	Remark      string `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Status      int32  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Type        int32  `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	UserID      string `protobuf:"bytes,11,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *EditAppVersionReq) Reset() {
	*x = EditAppVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAppVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAppVersionReq) ProtoMessage() {}

func (x *EditAppVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAppVersionReq.ProtoReflect.Descriptor instead.
func (*EditAppVersionReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{9}
}

func (x *EditAppVersionReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EditAppVersionReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *EditAppVersionReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EditAppVersionReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *EditAppVersionReq) GetIsforce() int32 {
	if x != nil {
		return x.Isforce
	}
	return 0
}

func (x *EditAppVersionReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditAppVersionReq) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *EditAppVersionReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *EditAppVersionReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EditAppVersionReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *EditAppVersionReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteAppVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	ID          string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID      string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *DeleteAppVersionReq) Reset() {
	*x = DeleteAppVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appversion_appversion_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppVersionReq) ProtoMessage() {}

func (x *DeleteAppVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_appversion_appversion_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppVersionReq.ProtoReflect.Descriptor instead.
func (*DeleteAppVersionReq) Descriptor() ([]byte, []int) {
	return file_appversion_appversion_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppVersionReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

func (x *DeleteAppVersionReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DeleteAppVersionReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_appversion_appversion_proto protoreflect.FileDescriptor

var file_appversion_appversion_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x70,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61,
	0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x5f,
	0x77, 0x73, 0x2f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xce, 0x02, 0x0a, 0x0a,
	0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x49, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x70, 0x70,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x95,
	0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x44, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x22, 0xab, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a,
	0x0b, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x94, 0x02, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x69, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0xa5, 0x02, 0x0a, 0x11,
	0x45, 0x64, 0x69, 0x74, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x61, 0x70, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appversion_appversion_proto_rawDescOnce sync.Once
	file_appversion_appversion_proto_rawDescData = file_appversion_appversion_proto_rawDesc
)

func file_appversion_appversion_proto_rawDescGZIP() []byte {
	file_appversion_appversion_proto_rawDescOnce.Do(func() {
		file_appversion_appversion_proto_rawDescData = protoimpl.X.CompressGZIP(file_appversion_appversion_proto_rawDescData)
	})
	return file_appversion_appversion_proto_rawDescData
}

var file_appversion_appversion_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_appversion_appversion_proto_goTypes = []interface{}{
	(*CommonResp)(nil),                // 0: appversion.CommonResp
	(*AppVersion)(nil),                // 1: appversion.AppVersion
	(*GetAppVersionByIDReq)(nil),      // 2: appversion.GetAppVersionByIDReq
	(*GetAppVersionByIDResp)(nil),     // 3: appversion.GetAppVersionByIDResp
	(*GetLatestAppVersionReq)(nil),    // 4: appversion.GetLatestAppVersionReq
	(*GetLatestAppVersionResp)(nil),   // 5: appversion.GetLatestAppVersionResp
	(*GetAppVersionsReq)(nil),         // 6: appversion.GetAppVersionsReq
	(*GetAppVersionsResp)(nil),        // 7: appversion.GetAppVersionsResp
	(*AddAppVersionReq)(nil),          // 8: appversion.AddAppVersionReq
	(*EditAppVersionReq)(nil),         // 9: appversion.EditAppVersionReq
	(*DeleteAppVersionReq)(nil),       // 10: appversion.DeleteAppVersionReq
	(*sdk_ws.RequestPagination)(nil),  // 11: server_api_params.RequestPagination
	(*sdk_ws.ResponsePagination)(nil), // 12: server_api_params.ResponsePagination
}
var file_appversion_appversion_proto_depIdxs = []int32{
	1,  // 0: appversion.GetAppVersionByIDResp.appversion:type_name -> appversion.AppVersion
	1,  // 1: appversion.GetLatestAppVersionResp.appversion:type_name -> appversion.AppVersion
	11, // 2: appversion.GetAppVersionsReq.Pagination:type_name -> server_api_params.RequestPagination
	1,  // 3: appversion.GetAppVersionsResp.appversions:type_name -> appversion.AppVersion
	12, // 4: appversion.GetAppVersionsResp.Pagination:type_name -> server_api_params.ResponsePagination
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_appversion_appversion_proto_init() }
func file_appversion_appversion_proto_init() {
	if File_appversion_appversion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_appversion_appversion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppVersionByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppVersionByIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestAppVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestAppVersionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppVersionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppVersionsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAppVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAppVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appversion_appversion_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appversion_appversion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appversion_appversion_proto_goTypes,
		DependencyIndexes: file_appversion_appversion_proto_depIdxs,
		MessageInfos:      file_appversion_appversion_proto_msgTypes,
	}.Build()
	File_appversion_appversion_proto = out.File
	file_appversion_appversion_proto_rawDesc = nil
	file_appversion_appversion_proto_goTypes = nil
	file_appversion_appversion_proto_depIdxs = nil
}
